############ BD ############
spring.datasource.url=jdbc:postgresql://localhost:5432/sotanofilm_db
spring.datasource.username=sotanofilmuser
spring.datasource.password=CaldasAntioquia16*
spring.datasource.driver-class-name=org.postgresql.Driver

############ Contextos ###########
spring.application.name=sotanofilmcatalogo
server.port=8085
server.servlet.context-path=/sotanofilmcatalogo

########### Ejecutables ##########
sotanofilm.ffmpeg = C:/Users/ancdi/Medios-DVD-BlueRay/ffmpeg-8.1.2-full_build/bin/ffmpeg.exe
sotanofilm.ffprobe = C:/Users/ancdi/Medios-DVD-BlueRay/ffmpeg-8.1.2-full_build/bin/ffprobe.exe
sotanofilm.ffplay = C:/Users/ancdi/Medios-DVD-BlueRay/ffmpeg-8.1.2-full_build/bin/ffplay.exe

########### Catalogo ##########
sotanofilm.carpeta.catalogo = D:/SotanoCatalogoDesarrollo/Catalogo-V9/1-Peliculas
sotanofilm.nombre.archivo.catalogo = /arbolCatalogo.txt

########### Catalogo Portable ##########
sotanofilm.portable.titulo.word.parrafo1 = Catalogo SotanoFilm
sotanofilm.portable.titulo.word.parrafo2 = Portable
sotanofilm.portable.tamanoCellIzquiedaCatalogo = 65%
sotanofilm.portable.tamanoCellDerechaCatalogo = 35%
sotanofilm.portable.width.imagen = 160
sotanofilm.portable.heigth.imagen = 160
sotanofilm.portable.catalogo = C:/SotanoCatalogoPortableDesarrollo/Catalogo-V2/1-Peliculas
sotanofilm.portable.catalogo.word = C:/SotanoFilmPortable/SotanoFilmCatalogoPortable/CatalogoWord
sotanofilm.portable.logo = LogoSotanoFilmPortableBannerDoradoTrasparente.png
sotanofilm.portable.width.logo = 300
sotanofilm.portable.heigth.logo = 58
sotanofilm.portable.crecion.codec = h264_nvenc
sotanofilm.portable.crecion.video.filter.720 = scale=1280:720,fps=24
sotanofilm.portable.crecion.video.filter.480 = scale=854x480,fps=24
sotanofilm.portable.crecion.calidad.constante = 28
sotanofilm.portable.crecion.optimizado.web = +faststart
